-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Event State Table
CREATE TABLE IF NOT EXISTS public.event_state (
    id INT PRIMARY KEY DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'setup' CHECK (status IN ('setup', 'active', 'paused', 'revealed')),
    timer_enabled BOOLEAN NOT NULL DEFAULT false,
    timer_seconds INT NOT NULL DEFAULT 0,
    spreadsheet_url TEXT DEFAULT '',
    last_synced_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    revealed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row_check CHECK (id = 1)
);

-- Seed initial event state row if missing
INSERT INTO public.event_state (id, status, updated_at)
VALUES (1, 'setup', NOW())
ON CONFLICT (id) DO NOTHING;

-- 2. Volunteers Table
CREATE TABLE IF NOT EXISTS public.volunteers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    centre TEXT NOT NULL,
    code TEXT UNIQUE NOT NULL,
    joined BOOLEAN NOT NULL DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_seed BOOLEAN NOT NULL DEFAULT false,
    assigned_color TEXT,
    completed_at TIMESTAMPTZ,
    completion_position INT,
    spreadsheet_source_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for efficient volunteer querying & login searches
CREATE INDEX IF NOT EXISTS idx_volunteers_name_centre ON public.volunteers (LOWER(name), LOWER(centre));
CREATE INDEX IF NOT EXISTS idx_volunteers_code ON public.volunteers (code);
CREATE INDEX IF NOT EXISTS idx_volunteers_joined ON public.volunteers (joined);

-- 3. Game Boards Table
CREATE TABLE IF NOT EXISTS public.game_boards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    volunteer_id BIGINT UNIQUE NOT NULL REFERENCES public.volunteers(id) ON DELETE CASCADE,
    cells JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Cell Entries Table
CREATE TABLE IF NOT EXISTS public.cell_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    volunteer_id BIGINT NOT NULL REFERENCES public.volunteers(id) ON DELETE CASCADE,
    cell_index INT NOT NULL CHECK (cell_index >= 0 AND cell_index < 25),
    partner_id BIGINT NOT NULL REFERENCES public.volunteers(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_volunteer_cell UNIQUE (volunteer_id, cell_index),
    CONSTRAINT no_self_entry CHECK (volunteer_id <> partner_id)
);

-- Indexes for entries and BINGO verification
CREATE INDEX IF NOT EXISTS idx_cell_entries_volunteer ON public.cell_entries (volunteer_id);
CREATE INDEX IF NOT EXISTS idx_cell_entries_partner ON public.cell_entries (partner_id);

-- Enable Supabase Realtime for reactive updates
ALTER PUBLICATION supabase_realtime ADD TABLE public.event_state;
ALTER PUBLICATION supabase_realtime ADD TABLE public.volunteers;
ALTER PUBLICATION supabase_realtime ADD TABLE public.cell_entries;
